name: üöÄ Deploy Laravel via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1Ô∏è‚É£ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2Ô∏è‚É£ Remove unnecessary files before upload
      - name: Clean project
        run: |
          rm -rf .git
          rm -rf node_modules
          rm -rf tests
          rm -rf storage/*.log
          rm -rf vendor

      # 3Ô∏è‚É£ Upload files via FTP
      - name: Upload files via FTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ftp.digitalnoticeboard.biz
          port: 22
          username: reportconsumer@reportconsumer.digitalnoticeboard.biz
          password: 5&gns~Kv&6^f

          local_path: ./
          remote_path: /home3/digituqa/reportconsumer.digitalnoticeboard.biz/

          sftp_only: false
          delete_remote_files: false
